// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using program_for_school_tests_ukr.Classes;

#nullable disable

namespace program_for_school_tests_ukr.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20231120065536_usercontext")]
    partial class usercontext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("program_for_school_tests_ukr.Classes.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("User_type").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("program_for_school_tests_ukr.Classes.Student", b =>
                {
                    b.HasBaseType("program_for_school_tests_ukr.Classes.User");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("program_for_school_tests_ukr.Classes.Teacher", b =>
                {
                    b.HasBaseType("program_for_school_tests_ukr.Classes.User");

                    b.HasDiscriminator().HasValue("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
